### PR TITLE
fix(TrackEventsV2): Error in python SDK track event endpoint.

### PR DESCRIPTION
**Pull request by giou-k**
### Problem
The client https://mlb-talonone-pot.us-east4.talon.oneis uses track event v2 endpoint via Python SDK. The event is tracked successfully inside of Talon.One, but the SDK is returning an error on its end which results in `ValueError: Invalid value for 'ledger_entries', must not be 'None'`

## Solution
Make ledger_entries not required. 

### Notes
[Slack discussion](https://talonone.slack.com/archives/CA71GMVPB/p1722962769761069)

* the node version of the docker image was updated because we used to use v14 - which is an old version and this was causing an error

### CODE REVIEW

**Comment by giou-k** [comment]
following this guide:
```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes
MINOR version when you add functionality in a backward compatible manner
PATCH version when you make backward compatible bug fixes
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```
https://semver.org/


I marked this versioning as a PATCH, but there might be the case that it would have been better to mark it as a MINOR AND PATCH, since I also generated all the new features that we had since the last release of the sdk. Nonetheless I think it is not that important even if I leave the versioning as it is.

let me know you opinion if any.

**Comment by kkupreeva** [comment]
Maybe change the minor version? Because new endpoints were added to the SDK but no backward incompatible changes

**Comment by rubyjohn93** [comment]
> Maybe change the minor version? Because new endpoints were added to the SDK but no backward incompatible changes

I think we usually go with major version unless its not just a bug fix.
Also it's been 2 months since we released last version.

**Comment by kkupreeva** [comment]
> > Maybe change the minor version? Because new endpoints were added to the SDK but no backward incompatible changes
> 
> I think we usually go with major version unless its not just a bug fix. Also it's been 2 months since we released last version.

I went with major version for other SDKs only because the update contained endpoints that were removed. The removed endpoint is clearly not a backward compatible change.

**Pull request merged**
